language: java
jdk: openjdk8
sudo: false
script: mvn package

deploy:
  provider: releases
  api_key:
    secure: HVaXYkjZe0YGdTm2PG+7gonFoyUCzqcza8f0n6ynsWb+pxkJv060qmWt7eU6leLmWUC0VJ8vKzvyX9s+OEaQbNU0VodfCToGqn+ioLof1v+NELdNoiDOGM77ENIuGvKPmu0JHOlmnUNOVyKWlP3b6KzzEASxj6XKf4EOGAtx3MbZichn904rajIaEdvgvquE0TdVU3K21PhPm7+wzCzFWc7cOO5LnkhqPWJSU1YYDfzaXa+tRmifBgg8Fc+3iTUIeO3LX4IKVOpXRnnStr8ZtTVtHo4HJGRCsZUHaddUy7OvRIjCE4UCnIMncau2pe73pyJKtMks2Y8khWKu6z7lQ/Q5jq6yw9z6gCrUa6Sg+B6rgA4DWlxm0WfTGpxwSgdAdnUva3RkSPtsFustPaNxExNgI7sTQa09ExsXITx/OG4J0qED//wHBmBTh+fah1mGtOv1dZKeHZi4BUj7lqzZomZkXEggeDwEC5SILSdVLCWf1/rFlMqTPNghlBZi7gAtGh0ZYxx3lX5X5D88ls+o5LljJsU79hw9is7oHTvk8GZN7EzDm9DNTj8KV/efiu4eA/RpKv3wOfWK6FGIjdydcW30ZBw8moOirClVz8lWfQsv8SxUmx12aknlgmHKXkvqHQL352ZfTCKrSeNjKgEeMv2lGuG5sN+8yOaWugnkkA8=
  file: target/audible-1.0-SNAPSHOT.jar
  on:
    repo: odnh/AudibleAppliances
